config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tweets/index'
  root to: "tweets#index"
  resources :tweets, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'search'
    end
    resources :comments, only: :create
      resource :items, only: [:show, :new, :create]
  end

  resources :items, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :orders, only: [:index, :create]
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_one :item
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :artist, length: {maximum: 40}
    validates :text, length: {maximum: 140}
  end

  validates :image, presence: true

  def self.search(search)
    if search != ""
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :move_to_index, only: [:show]

  def index
    @fourtweets = Tweet.includes(:item).order("created_at DESC").limit(4)
    @tweets = Tweet.includes(:item).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if current_user.id == tweet.user.id
      tweet.destroy
    end
      redirect_to root_path
  end

  def search
    @fourtweets = Tweet.search(params[:keyword]).order("created_at DESC").limit(4)
    @tweets = Tweet.search(params[:keyword]).order("created_at DESC")
  end

  private

  def tweet_params
    params.require(:tweet).permit(:artist, :text, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    @tweet = Tweet.find(params[:id])
    if @tweet.item != nil 
      if @tweet.item.order != nil
      redirect_to root_path
      end
    end
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with model: tweet, local: true do |f|%>

  <%= render 'devise/shared/error_messages', model: f.object %>

  <div class="field">
    <%= f.label :title, "アーティスト名" %>
      <span class="indispensable">必須</span></br>
    <%= f.text_field :artist, class: :form__text, placeholder:"最大40文字以内で入力して下さい" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "商品の詳細" %>
        <span class="indispensable">必須</span></br>
    <%= f.text_area :text, class: :form__text, placeholder:"最大140文字以内で入力して下さい" %>
  </div>

  <div class="field">
    <%= f.label :image, "商品の画像" %>
        <span class="indispensable">必須</span></br>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/tweets/_fourtweet.html.erb
<div class="tweet">
  <div class="tweet__body"> 
    <%= link_to image_tag(fourtweet.image, class: :tweet__img ), tweet_path(fourtweet) %>
        <div class="balloonoya">
          <div class="box_comment", id="comment">
            <%= link_to "#", class: :form__btn__comment do %>
              <i class="fa-regular fa-comment"></i>
                <span class="balloon">
                  <%= fourtweet.text %>
                </span>
            <% end %>
          </div>
        </div>  
      <%= link_to "#{fourtweet.user.nickname}さんのWANT LIST", "#", class: :tweet__user %> 
        <div class="balloonoya">
          <div class="comment_box hidden", id="comment_box">
            <i class="fa-regular fa-comment"></i>
          </div>
        </div>  
    <div class="tweettitle">
      <%= image_tag "wantlist.jpeg", class: :tweet__logo %> <%= link_to "#{fourtweet.artist}", tweet_path(fourtweet), class: :tweet__artist%>
    </div>  

    <div class="buy_action">
    <% if fourtweet.item != nil %>
      <% if fourtweet.item.order != nil %>
        <div class='sold-out'>
          <span>Successful !!</span>
        </div>
      <% end %> 
    <% end %> 
    
      <% if fourtweet.item != nil %>
        <% if fourtweet.item.order == nil %>
          <% if user_signed_in? && current_user.id == fourtweet.user.id %>
            <%= link_to tweet_items_path(fourtweet.id), class: :form__btn__buy do %>
              <i class="fa-solid fa-cart-shopping"></i>&emsp;Buy
            <% end %>
          <% elsif %>
            <%= link_to tweet_items_path(fourtweet.id), class: :form__btn__edit do %>
              <i class="fa-solid fa-wrench"></i>&emsp;Edit
            <% end %>
          <% end %>
        <% end %>
      <% end %> 
    </div>
  </div>
</div>

app/views/tweets/_head.html.erb
<div class="middle">
  <%= image_tag "recordmain.jpeg", class: "music-image" %> 
    <div class="music_inner">
      <div class="message">
        お探しの商品を投稿しましょう
      <div class="second_message_box">
        <div class="second_message">
        音楽に特化した、投稿型のフリーマーケットサイト<br>
        コンサート限定商品、プレミア商品など、探していた商品がきっと見つかる<br>
        </div>
      </div>
      </div>
      <% if user_signed_in? %>
        <%= link_to new_tweet_path, class: :form__btn__tweet do %>
          <i class="fa-solid fa-feather-pointed"></i>&emsp;Tweet
        <% end %>
      <% end %>
    </div>
      <form class="search-form" action="/tweets/search">
        <input class='input-box' placeholder='Search'>
        <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
        </button>
      </form>
</div>

app/views/tweets/_tweet.html.erb
<div class="tweet_eight">
  <div class="tweet__body"> 
    <%= link_to image_tag(tweet.image, class: :tweet__img ), tweet_path(tweet) %>
        <div class="balloonoya">
          <div class="box_comment", id="comment">
            <%= link_to "#", class: :form__btn__comment do %>
              <i class="fa-regular fa-comment"></i>
                <span class="balloon">
                  <%= tweet.text %>
                </span>
            <% end %>
          </div>
        </div>  
      <%= link_to "#{tweet.user.nickname}さんの WANT LIST", "#", class: :tweet__user__eight %> 
    <div class="tweettitle_eight">
      <%= image_tag "wantlist.jpeg", class: :tweet__logo__eight %> <%= link_to "#{tweet.artist}", tweet_path(tweet), class: :tweet__artist__eight %>
    </div>  

    <div class="buy_action">
    <% if tweet.item != nil %>
      <% if tweet.item.order != nil %>
        <div class='sold-out'>
          <span>Success ful !!</span>
        </div>
      <% end %> 
    <% end %> 
    
      <% if tweet.item != nil %>
        <% if tweet.item.order == nil %>
          <% if user_signed_in? && current_user.id == tweet.user.id %>
            <%= link_to tweet_items_path(tweet.id), class: :form__btn__buyeight do %>
              <i class="fa-solid fa-cart-shopping"></i>
            <% end %>
          <% elsif %>
            <%= link_to tweet_items_path(tweet.id), class: :form__btn__editeight do %>
              <i class="fa-solid fa-wrench"></i>
            <% end %>
          <% end %>
        <% end %>
      <% end %> 
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<main class="music_main">
  <%= render "head" %>

  <div class='item-contents'>
    <h2 class='newtweet_title'>NEW TWEET</h2>
  <div class="second_middle">
    <div class="tweet__wrapper", id="java">
      <%= render partial: 'fourtweet', collection: @fourtweets %>
    </div>
  </div>

  <div class='item-contents-list'>
    <h2 class='title-wantlist'>WANT LIST</h2>
  <div class="second_middle">
    <div class="tweet__wrapper">
      <%= render partial: 'tweet', collection: @tweets %>
    </div>
  </div>

</main>

app/views/tweets/new.html.erb
<div class="tweet_main">
  <div class="inner">
    <div class="form__wrapper">
      <div class="balloonoya"><h2 class="page-heading">New Tweet</h2>
            <span class="balloon">
              お探しの商品を投稿しましょう。</br>
              アーティスト名・商品の詳細・商品の画像を、下記フォームに入力して下さい。</p></br>
            </span>
      </div>
        <%= render partial: "form", locals: { tweet: @tweet } %>
    </div>
  </div>
</div>

app/views/tweets/search.html.erb
<main class="music_main">
  <%= render "head" %>

  <div class='item-contents'>
    <h2 class='newtweet_title'>NEW TWEET</h2>
  <div class="second_middle">
    <div class="tweet__wrapper", id="java">
      <%= render partial: 'fourtweet', collection: @fourtweets %>
    </div>
  </div>

  <div class='item-contents-list'>
    <h2 class='title-wantlist'>WANT LIST</h2>
  <div class="second_middle">
    <div class="tweet__wrapper">
      <%= render partial: 'tweet', collection: @tweets %>
    </div>
  </div>

</main>

app/views/tweets/show.html.erb
<main class="main">
  <div class="show_inner">

    <div class="tweet__show">
      <%= link_to "#{@tweet.user.nickname}  さんが探している商品", "#", class: :show__user %>
      <p class="tweet__hedding">
        <%= @tweet.artist %>
      </p>
      <div class="tweet__image__show">
        <%= image_tag @tweet.image.variant(resize:'300x300') %>
      </div>
      <div class="tweet__body">
        <div class="tweet__detail">
          <p class="tweet__title">商品の詳細</p>
          <p class="detail__text">
            <%= @tweet.text %>
          </p>
        </div>
      </div>
      <% unless @tweet.item != nil %>
        <% if user_signed_in? && current_user.id == @tweet.user.id %>
          <%= link_to tweet_path(@tweet.id), class: :form__btn__destroy, method: :delete do %>
            <i class="fa-solid fa-trash"></i>&emsp;Delete
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="tweet__comments">
      <span class="box-title">Comment</span>
      <% if user_signed_in? %>
        <%= form_with model: [@tweet, @comment], local: true do |f|%>
          <div class="comment_field">
            <p class="rules">⬅︎⬅︎⬅︎ こちらの商品を持っている方は、是非コメントしてみましょう。</br>
            交渉が成立したら、下の”出品"ボタンから商品を出品しましょう。</p></br>
            <%= render 'devise/shared/error_messages', model: f.object %>
            <%= f.label :comment %><br />
            <%= f.text_area :comment, id:"comment_content", :size=>"80", placeholder:"1回のコメントは、最大100文字以内で入力して下さい" %>
          </div>
          <div class="comment_submit", id="comment_submit">
            <%= f.submit "コメント送信", class: :commentnav__btn %>

            <% unless @tweet.item != nil %>
              <% if current_user.id != @tweet.user.id %>
              <%= link_to new_tweet_items_path(@tweet.id), class: :sellnav__btn do %>
                <i class="fa-regular fa-handshake"></i>&emsp;Sell
              <% end %>

              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <ul class="comments_lists">
        <% @comments.reverse.each do |comment| %>
        <% if comment.user.id == @tweet.user.id %>
          <li class="comments_list">
            <%= l comment.created_at %>
            <%= link_to "#{comment.user.nickname}さん", "#", class: :comment_user %>
              <div class="comment_com">
                <%= comment.comment %>
              </div>
          </li>
        </ul>
        <% else %>
        <ul class="comments_lists_other">
          <li class="comments_list_other">
            <%= l comment.created_at %>
            <%= link_to "#{comment.user.nickname}さん", "#", class: :comment_user_other %>
              <div class="comment_com_other">
                <%= comment.comment %>
              </div>
          </li>
        </ul>
        <% end %>
        <% end %>
    </div>
  </div>
</main>