config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tweets/index'
  root to: "tweets#index"
  resources :tweets, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'search'
    end
    resources :comments, only: :create
      resource :items, only: [:show, :new, :create]
  end

  resources :items, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :orders, only: [:index, :create]
  end
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  belongs_to :tweet
  has_one_attached :image
  has_one :order, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :shipping_fee_status
  belongs_to :prefecture

  validates :image, presence: true 

  with_options presence: true do
    validates :partner_nickname, length: {maximum: 10}
    validates :artist, length: {maximum: 40}
    validates :title, length: {maximum: 140}
  end

  with_options numericality: { other_than: 1, message: "を入力してください" } do
    validates :shipping_fee_status_id
    validates :prefecture_id
  end

  validates :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: "を¥300~¥9,999,999の間の半角数字を入力してください" }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :contributor_confirmation, only: [:new, :create]

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @item = @tweet.item.id
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(edit_params)
    if @item.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    if current_user.id == item.user.id
      item.destroy
    end
      redirect_to root_path
  end

  private

  def move_to_index
    @tweet = Tweet.find(params[:tweet_id])
  end

  def item_params
    params.require(:item).permit(:artist, :image, :title, :shipping_fee_status_id, :prefecture_id, :partner_nickname, :price).merge(user_id:current_user.id, tweet_id: params[:tweet_id])
  end

  def contributor_confirmation
     if current_user.id == @tweet.user.id
      redirect_to root_path
    end
  end

  def edit_params
    params.require(:item).permit(:artist, :image, :title, :shipping_fee_status_id, :prefecture_id, :partner_nickname, :price).merge(user_id:current_user.id)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with(model: [@tweet,@item], local: true) do |f| %>

    <%= render 'devise/shared/error_messages', model: f.object %>

    <div class="new-items">
      <div class="weight-bold-text">
        商品を探している方のニックネーム(投稿者)
        <span class="indispensable">必須</span>
      </div>  
      <%= f.text_area :partner_nickname, class:"items-text", id:"item-name", placeholder:"商品を探している方のニックネーム（必須)", maxlength:"10" %>
    </div>

    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        アーティスト名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :artist, class:"items-text", id:"item-name", placeholder:"アーティスト名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品タイトル
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :title, class:"items-text", id:"item-info", placeholder:"商品名、その他商品の説明（必須 140文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_fee_status_id, ShippingFeeStatus.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
      </div>
    </div>

    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "Submit" ,class:"sell-btn" %>
      <%=link_to 'Back', "/", class:"back-btn" %>
    </div>
    <% end %>
  </div>

  <footer class="items-sell-footer">
  </footer>
</div>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    
    <%= form_with model: @item, url:tweet_items_path, local: true do |f| %>

    <%= render 'devise/shared/error_messages', model: f.object %>

    <div class="new-items">
      <div class="weight-bold-text">
        商品を探している方のニックネーム(投稿者)
        <span class="indispensable">必須</span>
      </div>  
        <%= f.text_area :partner_nickname, class:"items-text", id:"item-name", placeholder:"商品を探している方のニックネーム（必須)", maxlength:"10" %>
    </div>

    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        アーティスト名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :artist, class:"items-text", id:"item-name", placeholder:"アーティスト名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品タイトル
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :title, class:"items-text", id:"item-info", placeholder:"商品タイトル、その他商品の説明（必須 140文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_fee_status_id, ShippingFeeStatus.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
      </div>
    </div>

    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "Submit" ,class:"sell-btn" %>
      <%=link_to 'Back', "/", class:"back-btn" %>
    </div>
    <% end %>
  </div>

  <footer class="items-sell-footer">
  </footer>
</div>

app/views/items/show.html.erb
<div class="item-show">
  <div class="item-box">
    <% unless @tweet.item.order != nil %>
      <% if user_signed_in? && current_user.id == @tweet.user.id %>
          <%= link_to item_orders_path(@item), class: :form__btn__buyer do %>
            <i class="fa-solid fa-cart-shopping"></i>&emsp; Buy Page!
          <% end %>
      <% elsif %>
        <div class="edit-destroy">
          <%= link_to edit_item_path(@item), class: :form__btn__showedit, method: :get do %>
            <i class="fa-solid fa-wrench"></i>&emsp;Edit Page!
          <% end %>
          <%= link_to item_path(@item), class: :form__btn__delete, method: :delete do %>
            <i class="fa-solid fa-trash"></i>&emsp;Delete Page!
          <% end %>
        </div>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= "商品説明" %></span>
    </div>

    <div class="item-price-box">
      <span class="item-price">
        Price&emsp;￥<%= @tweet.item.price %>
      </span>
    </div>

    <div class="item-img-content">
      <%= image_tag @tweet.item.image ,class:"item-box-img" %> 
    </div>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @tweet.item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @tweet.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">アーティスト名</th>
          <td class="detail-value"><%= @tweet.item.artist %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @tweet.item.shipping_fee_status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @tweet.item.prefecture.name  %></td>
        </tr>
      </tbody>
    </table>

    <div class="option">
      <div class="favorite-btn">
        <%# <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%> 
        <span>Good! 0</span>
      </div>
      <div class="report-btn">
        <%# <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%> 
        <span>Problem!</span>
      </div>
    </div>
  </div>
</div>